name: Build and test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        sanitizers: ["OFF", "ON"]
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libopenmpi-dev openmpi-bin freeglut3-dev xvfb
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITIZERS=${{ matrix.sanitizers }} -DBUILD_OPENGL=ON
      - name: Build with warnings as errors
        run: cmake --build build --parallel 2
      - name: Test
        run: ctest --test-dir build --output-on-failure
